[package]
name = "sudoku"
version = "0.1.0"
authors = ["Tomasz Necio <tomasz.necio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.9.0"
